services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=artembragin
      - DB_PASSWORD=1337
      - DB_NAME=auth_database
      - DB_SSLMODE=disable

  db:
    image: postgres:14.5-alpine
    restart: unless-stopped
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=1337
      - POSTGRES_USER=artembragin
      - POSTGRES_DB=auth_database

volumes:
  postgres_data: